name 'go-reminders'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures go-reminders'
long_description 'Installs/Configures go-reminders'
version '0.1.0'
depends 'artifactory-artifact'
